Repository FER-Universe/Aphrodite, pull requests merged in 2023-12, with the labels that each got.

#7 Aphrodite/docs/requirements
  requirements.txt
  run.sh
Labels: documentation

#8 delete backend/requirements
  .vscode/settings.json
  backend/main.py
  backend/requirements.txt
Labels: documentation

#10 Aphrodite/feat/request
  backend/apis/version1/openai_router.py
  backend/schemas/gpt_sch.py
  frontend/request.py
  requirements.txt
Labels: documentation, enhancement

#13 add pymysql
  requirements.txt
Labels: documentation

#14 feat: hello router client
  backend/apis/version1/hello_router.py
Labels: enhancement

#15 feat: update db router
  .gitignore
  backend/apis/data/database.py
  backend/apis/data/models.py
  backend/apis/version1/database_router.py
  backend/apis/version1/openai_router.py
Labels: enhancement

#16 feat: minor tuning of backend/main and others
  backend/apis/version1/emotion_router.py
  backend/apis/version1/openai_router.py
  backend/main.py
  run_backend.sh
Labels: enhancement, refactor

#17 feat: develop image generation funcs with SDXL
  .gitignore
  aphrodite/action/__init__.py
  aphrodite/action/base.py
  aphrodite/action/draw.py
  aphrodite/action/great_draw.py
  aphrodite/util/__init__.py
  aphrodite/util/model_configs.py
Labels: enhancement

#18 refactor: sdxl
  aphrodite/action/great_draw.py
Labels: refactor

#19 feat: aphrodite/feat/sdxl_with_lora
  aphrodite/action/great_draw.py
  aphrodite/util/__init__.py
  aphrodite/util/lora.py
  aphrodite/util/model_configs.py
  aphrodite/util/token.py
Labels: enhancement

#21 add delete function of database
  backend/apis/data/database.py
  backend/apis/version1/database_router.py
Labels: enhancement

#22 feat: update requirements and minor changes
  backend/apis/data/database.py
  requirements.txt
Labels: refactor
