Repository FER-Universe/Aphrodite, pull requests merged in 2024-02, with the labels that each got.

#27 add translation function / module list to install
  backend/apis/version1/clip_matching_router.py
  requirements.txt
Labels: documentation, enhancement

#28 hotfix: fix STT bug
  backend/apis/version1/stt_router.py
Labels: bug

#29 feat: response schema for database router
  backend/apis/data/database.py
  backend/apis/version1/database_router.py
  backend/main.py
  backend/schemas/dialogue_sch.py
Labels: enhancement

#30 V1/feat/streamlit interface for drawing
  aphrodite/action/__init__.py
  aphrodite/action/base.py
  aphrodite/action/drawing.py
  aphrodite/action/feeling.py
  frontend/chat.py
  frontend/draw.py
  run_backend.sh
  run_frontend.sh
Labels: enhancement

#32 add emotion classification function to chat mode
  backend/apis/version1/emotion_router.py
  backend/main.py
  backend/schemas/gpt_sch.py
  backend/utils/fer_util.py
  frontend/chat.py
  frontend/request.py
Labels: enhancement

#34 V1/feat/chatbot refactoring
  backend/apis/version1/emotion_router.py
  backend/main.py
  frontend/chat.py
  run_backend.sh
Labels: refactor

#35 Add persona option to chatbot
  backend/apis/version1/emotion_router.py
  backend/schemas/gpt_sch.py
  frontend/chat.py
  frontend/request.py
  run_frontend.sh
Labels: enhancement

#36 refactor: logging
  aphrodite/action/retrieve.py
  aphrodite/llm/base.py
  backend/apis/data/database.py
  backend/apis/version1/clip_matching_router.py
  backend/apis/version1/emotion_router.py
  backend/apis/version1/hello_router.py
  backend/apis/version1/stt_router.py
  frontend/communicate.py
  frontend/request.py
Labels: refactor

#37 update assets: emotion templates
  backend/apis/version1/emotion_router.py
  backend/utils/fer_util.py
  frontend/chat.py
  frontend/file.py
Labels: refactor

#38 add color image for expressing emotion"
  backend/apis/version1/emotion_router.py
  frontend/chat.py
Labels: enhancement
